# 변수 선언

**변수의 선언은** **var, const, let 키워드로 할 수 있으며, ES6에서 const와 let이 추가되었다.**

자바스크립트에서 변수 선언은 `선언 → 초기화` 단계를 거쳐 수행된다.

- **선언 단계**: 변수명을 등록하여 자바스크립트 엔진에 변수의 존재를 알린다.
- **초기화 단계**: 값을 저장하기 위한 메모리 공간을 확보하고 암묵적으로 undefined를 할당해 초기화한다.

# 변수 할당

**변수에 값을 할당 할 때에는 할당 연산자(=)를 사용한다.**

```jsx
var cow // 변수 선언
cow = 'coin on web' // 값의 할당

var cow = 'coin on web' // 변수 선언과 할당
```

## 호이스팅

★**변수 선언이 어디에 있든 상관없이 다른 코드보다 먼저 실행되는 특징을 호이스팅
(hoisting)이라 한다.**


# 동기/비동기

## 자바스크립트는 동기식 언어이다.

- 자바스크립트는 한 번에 하나의 작업을 수행한다.
- **한 작업이 실행되는 동안 다른 작업은 멈춘 상태를 유지하고 자신의 차례를 기다리는 것**을 말한다. 마치 음식점에 여러 사람들과 갔을 때, 키오스크를 이용하여 한 사람씩 결제하는 것과 유사하다. 이러한 동작을 **단일 스레드(싱글 스레드), 동기(Synchronous)**라고 부른다.

```jsx
console.log("hi");
console.log("hello");
console.log("bye");
hi
hello
bye
```

### **그렇다면 왜 이렇게 나오는 것일까?**

그것은 바로 Javascript의 Engine(V8)을 까 보면(?) 알 수 있다.

![https://blog.kakaocdn.net/dn/8XRnQ/btqFQKwWMDa/pX0jhdyajUYb1OOQKMfR01/img.png](https://blog.kakaocdn.net/dn/8XRnQ/btqFQKwWMDa/pX0jhdyajUYb1OOQKMfR01/img.png)

출처 : https://blog.sessionstack.com/how-does-javascript-actually-work-part-1-b0bacc073cf

일단 **Memory Heap**과 **Call Stack**은 **자바스크립트의 엔진의** **주요 구성 요소**이다.

### **Memory Heap이란?**

변수와 객체의 메모리 할당을 담당하는 곳을 말한다.

### **Call Stack이란?**

함수가 호출이 되면 쌓이는 곳이다. 대신 함수가 쌓이는 순서와는 반대로 실행된다.

자바스크립트에서 함수를 호출하면 **Call Stack**이라는 곳에 호출 순서대로 차곡차곡 쌓인다.

그러고 나서, **Stack은** **맨 마지막에 호출된 함수가 맨 먼저 반환**한다.

**List in Frist Out**, 먼저 들어온 것이 먼저 나간다라는 의미로, **LIFO 구조**라고 부른다.

![https://blog.kakaocdn.net/dn/kZQ9V/btqFPr59AGn/ryDxH7Z7kHQvWSkHWXeuRK/img.png](https://blog.kakaocdn.net/dn/kZQ9V/btqFPr59AGn/ryDxH7Z7kHQvWSkHWXeuRK/img.png)

![https://blog.kakaocdn.net/dn/cO5t3u/btqFQ9QI74a/A1XOIsSA4zMyyk2SdQVkJK/img.png](https://blog.kakaocdn.net/dn/cO5t3u/btqFQ9QI74a/A1XOIsSA4zMyyk2SdQVkJK/img.png)

![https://blog.kakaocdn.net/dn/Jem4D/btqFP9KFt2v/lroQOM4zkjeNOexK6qDpT1/img.png](https://blog.kakaocdn.net/dn/Jem4D/btqFP9KFt2v/lroQOM4zkjeNOexK6qDpT1/img.png)

이렇게 순서대로 처음에 console.log("hi")가 호출되면서 Call Stack에 먼저 쌓이고, hi를 반환하면 console.log("hi")는 Call Stack에서 사라진다.

하지만, hi를 반환하기 전까지 다음 작업은 수행할 수 없다.

이 순서대로 console.log("hi")가 사라지고 hi를 반환한다.

그러고 나서, console.log("hello")가 쌓이고 hello를 반환하면, console.log("hello")가 사라진다.

또, 그러고 나서 console.log("bye")가 쌓이고 bye를 반환하면 console.log("bye")가 마지막으로 사라진다.

이러한 방식으로 진행되기 때문에 콘솔 창에 순서대로 "hi", "hello", "bye"가 찍히는 것이다.

**출처:[https://ljtaek2.tistory.com/142](https://ljtaek2.tistory.com/142)**



# 블로킹/논블로킹

![Untitled](%E1%84%87%E1%85%B3%E1%86%AF%E1%84%85%E1%85%A9%E1%84%8F%E1%85%B5%E1%86%BC%20%E1%84%82%E1%85%A9%E1%86%AB%E1%84%87%E1%85%B3%E1%86%AF%E1%84%85%E1%85%A9%E1%84%8F%E1%85%B5%E1%86%BC%20e924b55ccb794129a0c76737fd967491/Untitled.png)

우리가 커피샵의 대기열에 줄을 서 있는 손님이라고 생각해 봅시다. 

앞 손님이 커피를 주문하고, 주문한 커피를 받을 때까지, 줄에 서 있는 여러분이 주문조차 할 수 없다면 그 커피샵은 아무도 가려고 하지 않을거에요.

이를 우리는 **blocking** 이라고 부른다. 동기적인 작업에 따라 이후 작업이 "막히게 된 것"이다.

반대로, 작업이 막히지 않으면, **Non-blocking**이라고 부릅니다.

# Callback/Promise/Async,Await

### Callback

자바스크립트에서는 함수가 받아들이는 값을 int, string 형 뿐만 아니라 함수로도 받아들일 수 있습니다. 인자로 받아들인 함수를 다시 호출하는 기능을 callback이라고 부릅니다.

### Callback 예제

```jsx
function add5(a, callback) {
  setTimeout(() => callback(a + 5), 100)
// 100ms가 지난 후 함수로 입력받은 callback에 a + 10값을 다시 입력하여 callback함수 호출
}
add5(10, function (res) {// add5가 입력받는 callback함수 정의 부분
  console.log(res)
});

```

add5를 호출하는 부분을 보시면 첫 번째 인자로 숫자 5, 두 번째로는 함수를 생성하여 전달하는 것을 볼 수 있습니다. add5 함수 내부에서는 입력 받은 함수 callback에 a + 5를 하여 다시 호출하게 됩니다.

### Callback Hell

Callback이란 처음엔 조금 어렵지만 한번 이해하게 되면 굉장히 편한 기능입니다. 하지만 callback은 연속적으로 사용하게 되면 유지보수가 힘들어 진다는 치명적인 단점이 존재합니다

이번에는 위의 예제에서 만든 add5를 연속적으로 호출하여 10에 5 + 5 + 5 + 5 를 하는 코드입니다.

```jsx
add5(10, res => {
  add5(res, res => {
    add5(res, res => {
      add5(res, res => {
        console.log(res)
      })
    })
  })
})

```

단순히 더하기만 하는 코드지만 함수를 재귀적으로 여러번 호출하기 때문에 다소 복잡해 보입니다.

실제로 로그인 기능을 구현할 때 로그인 정보를 받아들여 비밀번호를 확인하고, 옳다면 유저 정보를 가져오고 틀리다면 에러 메시지를 출력하는 등 `if-else`문이 callback 중간 중간에 들어가야 하는 경우가 자주 있습니다.

![https://techlog.io/gallery/javascript/callback-hell.gif](https://techlog.io/gallery/javascript/callback-hell.gif)

따라서 callback을 4번5번 연속적으로 호출하게 될 경우 callback hell을 맛보실 수 있게 됩니다.

### Promises

Promise란 기본적으로 callback이 하는 일과 같습니다. 다만 차이점이라면 Promise는 작업이 끝난 후 실행할 함수를 제공하는 것이 아니라 Promise 자체 메소드인 `.then()`을 호출하게 됩니다.

### Promise 특징

```jsx
function add10(a) {
  return new Promise(resolve => setTimeout(() => resolve(a + 10), 100));
}//Promise사용 시 작업이 끝났음을 알려주는 resolve를 인자로 받아들임.

add10(10)
  .then(add10)
  .then(add10)
  .then(add10)
  .then((res) => console.log(res))

```

Promise는 then()과 같은 메소드를 연속적으로 사용이 가능한 이점을 가지고 있습니다. 따라서 callback을 사용했을 때와는 다르게 코드를 작성하고 이해하기가 한결 쉬워졌습니다.

이처럼 메소드를 연속적으로 사용하는 chaining이 가능한 이유는 add10 함수가 결과값을 Promise로 리턴하기 때문입니다. 실제로 add10의 결과값을 출력해보면 값이 다음과 같이 출력되는 것을 볼 수 있습니다.

```jsx
console.log(add10(10));
>> Promise { <pending> }

```

### Promise에서의 예외 처리

```jsx
add10(10)
  .then((res) => {
        throw 'test error';
    })
  .catch((err) => console.log(err));

```

Promise에서는 작업이 실패하였을 경우 자동으로 `.catch()` 메소드가 호출되게 됩니다. 따라서 callback과 같이 함수 호출 중간에 if-else를 사용하는 것이 아닌 .catch()로 한번에 해결할 수 있는 장점이 있습니다.

```jsx
try {
  add10(10)
        .then((res) => {
            throw 'test error';
        })
} catch(err) {
  console.log(err)
}

```

기존 `try-catch`를 이용해서도 예외 처리가 가능하지만 자바스크립트에서는 Promise의 catch를 사용 하라는 warning message를 출력하게 됩니다.

### Async/Await

NodeJs 버전 7.6부터 구현된 기능이며 Async/Await를 사용하면 Promise에 비해 보다 쉽게 비동기적인 상황을 표현할 수 있습니다.

```jsx
async function f1() {
  const a = await add10(10);
  const b = await add10(a);
  console.log(a, b)
}
f1();

```

Async와 Await을 사용하려면 우선 사용할 함수 앞에 async라는 키워드를 붙여 사용해야 하며 선언된 async 함수 안에서만 await 키워드를 사용할 수 있습니다.

await은 함수의 작업이 끝나고 결과값을 반환할 때까지 대기하게 되며 결과 값이 리턴된다면 다음 작업으로 넘어가게 됩니다.

### Async/Await에서의 예외 처리

```jsx
async function f2() {
  const a = await add10(10).then(res => res);
  const b = await add10(a).catch(err => err);
  console.log(a, b)
}
f2();

```

위의 예제에서는 add10이 Promise를 리턴하므로 Promise가 지원하는 메소드들을 바로 사용할 수 있습니다. 따라서 .catch()를 이용하여 예외 처리가 가능합니다.

```jsx
async function f3() {
  try {
    const a = await add10(10)
    const b = await add10(a)
    console.log(a, b)
  } catch(err) {
    console.log(err)
  }
}
f3();

```

또는 기존과 같은 방식의 try-catch를 이용한 예외 처리를 할 수 있습니다.